CREATE DATABASE Alkemy;

USE Alkemy;

CREATE TABLE Users (
  id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(25) NOT NULL,
  lastname VARCHAR(25) NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(60) NOT NULL,
  balance DECIMAL NOT NULL DEFAULT 0
);

CREATE TABLE Types (
  id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  type VARCHAR (25) UNIQUE NOT NULL
);

CREATE TABLE Categories (
  id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE Operations (
  id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  concept VARCHAR(75) NOT NULL,
  amount DECIMAL NOT NULL,
  date DATE NOT NULL,
  typeID INTEGER NOT NULL,
  categoryID INTEGER NOT NULL,
  userID INTEGER NOT NULL,
  FOREIGN KEY (typeID) REFERENCES Types(id),
  FOREIGN KEY (categoryID) REFERENCES Categories(id),
  FOREIGN KEY (userID) REFERENCES Users(id)
);
